new_block_face(Point(3.2,0,0),Point(3.2,0,1500),Point(113,0,1500),Point(113,0,0))
new_block_face(Point(0.01,0,0),Point(0.01,0,1500),Point(3.2,0,1500),Point(3.2,0,0))
block("Block_1").set_size(100,20,2,1)
block("Block_2").set_size(100,5,2,1)
block("Block_1").set_name("cil")
block("Block_2").set_name("CHT")

patch("cil",1,1).set_type("MIR")
patch("cil",2,1).set_type("MIR")
patch("cil",3,1).set_type("SOL")
patch("cil",4,1).set_type("SOL")
patch("cil",5,1).set_type("INL")
patch("cil",6,1).set_type("OUT")

patch("CHT",1,1).set_type("MIR")
patch("CHT",2,1).set_type("MIR")
patch("CHT",3,1).set_type("MIR")
patch("CHT",4,1).set_type("SOL")
patch("CHT",5,1).set_type("INL")
patch("CHT",6,1).set_type("OUT")

patch("cil",3,1).set_type("UND")
patch("CHT",4,1).set_type("UND")

create_clustering_group("top")
clustering_group("top").add_segment(segment("cil",1,4,1),0)
clustering_group("top").add_segment(segment("cil",1,3,1),0)
clustering_group("top").cluster_start(0.2)
#connect_edges(edge("cil",1,3),edge("CHT",1,4),"ALL",1E-006)
block_by_face_rotation(face("cil",1),"Z",5,0,1)
block_by_face_rotation(face("CHT",1),"Z",5,0,1)
create_block_group("Solid")
create_block_group("Fluid")
block_group("Solid").add_block(block("CHT"))
block("CHT").set_type(1)
block_group("Fluid").add_block(block("cil"))
search_connections(1E-005)