FHX.set_precision_mode("double")
FHX.set_unit_ratio(0.001)
FHX.set_time_configuration(STEADY)
FHX.select_fluid_from_database(0,"AIR(Perfect)")
FHX.set_mathematical_model(0,LAMINAR)
FHX.set_gravity_flag(0,1)
FHX.set_gravity_vector(0,Point(0,0,-9.81))
FHX.set_gravity_flag(0,1)
FHX.set_gravity_vector(0,Point(0,0,-9.81))
FHX.set_reference_velocity(0,0.1)
FHX.set_preconditioning(0,1)
FHX.get_bc_patch(0,5).set_bc_type([124,10]) #Inlet
FHX.get_bc_patch(0,5).set_parameter_value("Absolute Total Pressure",101325)
FHX.get_bc_patch(0,5).set_parameter_value("Absolute Total Temperature",300)
FHX.get_bc_patch(0,4).set_bc_type([25,110]) #outlet
FHX.get_bc_patch(0,4).set_parameter_value("Static Pressure",101325 - 9.81*1.17507455268*1.5)
FHX.get_bc_patch(0,0).set_bc_type([113,0])
FHX.get_bc_patch(0,0).set_compute_force_and_torque_flag(0)
FHX.get_bc_patch(0,1).set_bc_type([113,0])
FHX.get_bc_patch(0,1).set_compute_force_and_torque_flag(0)
FHX.get_initial_solution(0).set_pressure(101325)
FHX.get_initial_solution(0).set_temperature(300)
FHX.get_initial_solution(0).set_coord_system("rel")
FHX.get_initial_solution(0).set_velocity(Vector(0,0,0))
FHX.set_MG_flag(1)
FHX.set_MG_correction_damping(2)
FHX.set_MG_level_number(4)
FHX.set_MG_number_of_cycles(1000)
FHX.set_MG_convergence_criteria(-3.5)
FHX.set_CFL_number(0,2.8)
FHX.set_preconditioning_characteristic_velocity(0,1)
FHX.set_numerical_scheme_accuracy(0,SECOND_ORDER)
FHX.set_preconditioning_characteristic_velocity(0,0.4)
FHX.set_nb_iter_max(100000)
FHX.set_convergence_criteria(-8)
FHX.set_output_writing_frequency(1000)
FHX.set_computation_name(0,"Noheat")

FHX.new_computation("264_1stOrder")
FHX.get_bc_patch(0,0).set_bc_type([110,0])
FHX.get_bc_patch(0,0).set_parameter_value("Heat-Flux",264)
FHX.get_bc_patch(0,0).set_compute_force_and_torque_flag(0)
FHX.set_numerical_scheme_accuracy(0,SECOND_ORDER)
